using System.Collections.Generic;
using System.Collections.Immutable;
using NBitcoin;
using Stratis.SmartContracts.Core;
using Stratis.SmartContracts.Core.Exceptions;
using Stratis.SmartContracts.Core.State;
using Stratis.SmartContracts.Core.State.AccountAbstractionLayer;
using Stratis.SmartContracts.Executor.Reflection.ContractLogging;
using Stratis.SmartContracts.Executor.Reflection.Serialization;

namespace Stratis.SmartContracts.Executor.Reflection
{
    /// <summary>
    /// Represents the current state of the world during a contract execution.
    /// <para>
    /// The state contains several components:
    /// </para>
    /// - The state repository, which contains global account, code, and contract data.
    /// - Internal transfers, which are transfers generated internally by contracts.
    /// - Balance state, which represents the intermediate state of the balances based on the internal transfers list.
    /// - The log holder, which contains logs generated by contracts during execution.
    /// <para>
    /// When a message is applied to the state, the state is updated if the application was successful. Otherwise, the state
    /// is rolled back to a previous snapshot. This works equally for nested state transitions generated by internal creates,
    /// calls and transfers.
    /// </para>
    /// </summary>
    public class State : IState
    {
        /// <summary>
        /// A snapshot of the world state during a contract execution.
        /// </summary>
        private class StateSnapshot
        {
            public StateSnapshot(IContractLogHolder logHolder, List<TransferInfo> internalTransfers, ulong nonce, byte[] root)
            {
                this.Logs = logHolder.GetRawLogs().ToImmutableList();
                this.InternalTransfers = internalTransfers.ToImmutableList();
                this.Nonce = nonce;
                this.Root = root;
            }

            public byte[] Root { get; }

            public ImmutableList<RawLog> Logs { get; }

            public ImmutableList<TransferInfo> InternalTransfers { get; }

            public ulong Nonce { get; }
        }

        public State(
            InternalTransactionExecutorFactory internalTransactionExecutorFactory,
            ISmartContractVirtualMachine vm,
            IContractStateRepository repository,
            IBlock block,
            Network network,
            ulong txAmount,
            uint256 transactionHash,
            IAddressGenerator addressGenerator)
        {
            this.Repository = repository;
            this.LogHolder = new ContractLogHolder(network);
            this.InternalTransfers = new List<TransferInfo>();
            this.BalanceState = new BalanceState(this.Repository, txAmount, this.InternalTransfers);
            this.Network = network;
            this.Nonce = 0;
            this.Block = block;
            this.TransactionHash = transactionHash;
            this.AddressGenerator = addressGenerator;
            this.InternalTransactionExecutorFactory = internalTransactionExecutorFactory;
            this.Vm = vm;
        }

        public IAddressGenerator AddressGenerator { get; }

        public uint256 TransactionHash { get; }

        public IBlock Block { get; }

        public ulong Nonce { get; private set; }

        public Network Network { get; }

        public IContractStateRepository Repository { get; }

        public IContractLogHolder LogHolder { get; }

        public BalanceState BalanceState { get; }

        public List<TransferInfo> InternalTransfers { get; }

        public InternalTransactionExecutorFactory InternalTransactionExecutorFactory { get; }

        public ISmartContractVirtualMachine Vm { get; }

        private ulong GetNonceAndIncrement()
        {
            return this.Nonce++;
        }

        /// <summary>
        /// Returns a new contract address and increments the address generation nonce.
        /// </summary>
        private uint160 GetNewAddress()
        {
            return this.AddressGenerator.GenerateAddress(this.TransactionHash, this.GetNonceAndIncrement());
        }

        /// <summary>
        /// Reverts the state to a previous snapshot.
        /// </summary>
        private void Rollback(StateSnapshot snapshot)
        {
            ((ContractStateRepositoryRoot) this.Repository).SyncToRoot(snapshot.Root);

            // Reset the nonce
            this.Nonce = snapshot.Nonce;

            // Rollback internal transfers
            this.InternalTransfers.Clear();
            this.InternalTransfers.AddRange(snapshot.InternalTransfers);
            
            // Rollback logs
            this.LogHolder.Clear();
            this.LogHolder.AddRawLogs(snapshot.Logs);
        }

        /// <summary>
        /// Snapshots the existing state.
        /// </summary>
        private StateSnapshot TakeSnapshot()
        {
            var root = ((ContractStateRepositoryRoot) this.Repository).Root;
            return new StateSnapshot(this.LogHolder, this.InternalTransfers, this.Nonce, root);
        }

        /// <summary>
        /// Applies an externally generated contract creation message to the current state.
        /// </summary>
        public StateTransitionResult Apply(ExternalCreateMessage message)
        {
            var stateSnapshot = this.TakeSnapshot();

            var address = this.GetNewAddress();

            var gasMeter = new GasMeter(message.GasLimit);

            gasMeter.Spend((Gas)GasPriceList.BaseCost);

            var contractState = this.ContractState(gasMeter, address, message, this.Repository);

            var result = this.Vm.Create(this.Repository, message.Method, contractState, message.Code);

            var revert = result.ExecutionException != null;

            if (revert)
            {
                this.Rollback(stateSnapshot);
            }
            else
            {
                this.Repository.Commit();
            }

            return new StateTransitionResult
            {
                Success = !revert,
                GasConsumed = gasMeter.GasConsumed,
                VmExecutionResult = result,
                ContractAddress = address,
                Kind = StateTransitionKind.Create,
                TransferResult = null
            };
        }

        /// <summary>
        /// Applies an internally generated contract creation message to the current state.
        /// </summary>
        public StateTransitionResult Apply(InternalCreateMessage message)
        {
            var enoughBalance = this.EnsureContractHasEnoughBalance(message.From, message.Amount);

            if (!enoughBalance)
                throw new InsufficientBalanceException();

            var stateSnapshot = this.TakeSnapshot();

            // Get the code using the sender. We are creating an instance of a Type in its assembly.
            byte[] contractCode = this.Repository.GetCode(message.From);

            var address = this.GetNewAddress();
            
            var gasMeter = new GasMeter(message.GasLimit);

            gasMeter.Spend((Gas)GasPriceList.BaseCost);

            var contractState = this.ContractState(gasMeter, address, message, this.Repository);

            var result = this.Vm.Create(this.Repository, message.Method, contractState, contractCode, message.Type);

            var revert = result.ExecutionException != null;

            if (revert)
            {
                this.Rollback(stateSnapshot);
            }
            else
            {
                this.Repository.Commit();

                this.InternalTransfers.Add(new TransferInfo
                {
                    From = message.From,
                    To = address,
                    Value = message.Amount
                });
            }

            CreateResult createResult = revert
                ? CreateResult.Failed()
                : CreateResult.Succeeded(address.ToAddress(this.Network));

            return new StateTransitionResult
            {
                Success = !revert,
                GasConsumed = gasMeter.GasConsumed,
                VmExecutionResult = result,
                ContractAddress = address,
                Kind = StateTransitionKind.InternalCreate,
                TransferResult = null,
                CreateResult = createResult
            };
        }

        /// <summary>
        /// Applies an internally generated contract method call message to the current state.
        /// </summary>
        public StateTransitionResult Apply(InternalCallMessage message)
        {
            var enoughBalance = this.EnsureContractHasEnoughBalance(message.From, message.Amount);

            if (!enoughBalance)
                throw new InsufficientBalanceException();

            byte[] contractCode = this.Repository.GetCode(message.To);

            if (contractCode == null || contractCode.Length == 0)
            {
                // No contract code at this address
                return new StateTransitionResult
                {
                    Success = false,
                    GasConsumed = (Gas)0,
                    Kind = StateTransitionKind.None,
                    TransferResult = TransferResult.Empty(),
                    ContractAddress = message.To
                };
            }

            var stateSnapshot = this.TakeSnapshot();

            var type = this.Repository.GetContractType(message.To);

            var gasMeter = new GasMeter(message.GasLimit);

            gasMeter.Spend((Gas)GasPriceList.BaseCost);

            var contractState = this.ContractState(gasMeter, message.To, message, this.Repository);

            var result = this.Vm.ExecuteMethod(this.Repository, message.Method, contractState, contractCode, type);

            var revert = result.ExecutionException != null;

            if (revert)
            {
                this.Rollback(stateSnapshot);
            }
            else
            {
                this.Repository.Commit();

                // Only append internal value transfer if the execution was successful.
                this.InternalTransfers.Add(new TransferInfo
                {
                    From = message.From,
                    To = message.To,
                    Value = message.Amount
                });
            }

            return new StateTransitionResult
            {
                Success = !revert,
                GasConsumed = gasMeter.GasConsumed,
                VmExecutionResult = result,
                Kind = StateTransitionKind.Call,
                TransferResult = TransferResult.Transferred(result.Result),
                ContractAddress = message.To
            };
        }

        /// <summary>
        /// Applies an externally generated contract method call message to the current state.
        /// </summary>
        public StateTransitionResult Apply(ExternalCallMessage message)
        {
            byte[] contractCode = this.Repository.GetCode(message.To);

            if (contractCode == null || contractCode.Length == 0)
            {
                // No contract code at this address
                return new StateTransitionResult
                {
                    Success = false,
                    GasConsumed = (Gas)0,
                    Kind = StateTransitionKind.None,
                    TransferResult = TransferResult.Empty(),
                    ContractAddress = message.To
                };
            }

            var stateSnapshot = this.TakeSnapshot();

            var type = this.Repository.GetContractType(message.To);

            var gasMeter = new GasMeter(message.GasLimit);

            gasMeter.Spend((Gas)GasPriceList.BaseCost);

            var contractState = this.ContractState(gasMeter, message.To, message, this.Repository);

            var result = this.Vm.ExecuteMethod(this.Repository, message.Method, contractState, contractCode, type);

            var revert = result.ExecutionException != null;

            if (revert)
            {
                this.Rollback(stateSnapshot);
            }
            else
            {
                // External call, so we don't need to add the transfer
                this.Repository.Commit();
            }

            return new StateTransitionResult
            {
                Success = !revert,
                GasConsumed = gasMeter.GasConsumed,
                VmExecutionResult = result,
                Kind = StateTransitionKind.Call,
                TransferResult = TransferResult.Transferred(result.Result),
                ContractAddress = message.To
            };
        }

        /// <summary>
        /// Applies an internally generated contract funds transfer message to the current state.
        /// </summary>
        public StateTransitionResult Apply(ContractTransferMessage message)
        {
            var enoughBalance = this.EnsureContractHasEnoughBalance(message.From, message.Amount);

            if (!enoughBalance)
                throw new InsufficientBalanceException();

            // If it's not a contract, create a regular P2PKH tx
            // If it is a contract, do a regular contract call
            byte[] contractCode = this.Repository.GetCode(message.To);

            if (contractCode == null || contractCode.Length == 0)
            {
                // No contract at this address, create a regular P2PKH xfer
                this.InternalTransfers.Add(new TransferInfo
                {
                    From = message.From,
                    To = message.To,
                    Value = message.Amount
                });

                return new StateTransitionResult
                {
                    Success = true,
                    GasConsumed = (Gas)0,
                    Kind = StateTransitionKind.Transfer,
                    TransferResult = TransferResult.Empty(),
                    ContractAddress = message.To
                };
            }

            return this.Apply(message as InternalCallMessage);
        }

        /// <summary>
        /// Sets up a new <see cref="ISmartContractState"/> based on the current state.
        /// </summary>        
        private ISmartContractState ContractState(IGasMeter gasMeter, uint160 address, BaseMessage message, IContractStateRepository repository)
        {
            IPersistenceStrategy persistenceStrategy = new MeteredPersistenceStrategy(repository, gasMeter, new BasicKeyEncodingStrategy());

            var persistentState = new PersistentState(persistenceStrategy, new ContractPrimitiveSerializer(this.Network), address);

            var contractState = new SmartContractState(
                this.Block,
                new Message(
                    address.ToAddress(this.Network),
                    message.From.ToAddress(this.Network),
                    message.Amount
                ),
                persistentState,
                gasMeter,
                this.LogHolder,
                this.InternalTransactionExecutorFactory.Create(this),
                new InternalHashHelper(),
                () => this.BalanceState.GetBalance(address));

            return contractState;
        }

        /// <summary>
        /// Throws an exception if a contract doesn't have a high enough balance to make this transaction.
        /// </summary>
        private bool EnsureContractHasEnoughBalance(uint160 contractAddress, ulong amountToTransfer)
        {
            ulong balance = this.BalanceState.GetBalance(contractAddress);

            return balance >= amountToTransfer;
        }
    }
}